---
- name: Create front end configmap
  community.kubernetes.k8s:
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: student-config
      data:
        db-url: students
- name: Create front end secret
  community.kubernetes.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: student-credentials
      type: Opaque
      data:
        username: cm9vdA==
        password: TXlTUUwjMTY=
- name: Create front end app service
  community.kubernetes.k8s:
    definition:
      kind: Deployment
      apiVersion: v1
      kind: Service
      metadata:
        name: student-service
        labels:
          app: student-service
      spec:
        type: ClusterIP
        selector:
          app: student-app
        ports:
        - port: 8080
          protocol: TCP
          targetPort: 8080
- name: Create front end app deployment
  community.kubernetes.k8s:
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: student-deployment
        labels:
          app: student-deployment
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: student-app
        template:
          metadata:
            labels:
              app: student-app
          spec:
            containers:
            - name: my-app-container
              image: pallavw/student-app
              ports:
              - containerPort: 8080  
