# permissions for end users to view frontends.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: frontend-viewer-role
rules:
- apiGroups:
  - studentapps.studentapp.persistent.com
  resources:
  - frontends
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - studentapps.studentapp.persistent.com
  resources:
  - frontends/status
  verbs:
  - get
