# permissions for end users to edit frontends.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: frontend-editor-role
rules:
- apiGroups:
  - studentapps.studentapp.persistent.com
  resources:
  - frontends
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - studentapps.studentapp.persistent.com
  resources:
  - frontends/status
  verbs:
  - get
