apiVersion: studentapp.persistent.com/v1apha1
kind: CustomResourceDefinition
metadata:
  name: databases.studentapp.persistent.com
spec:
  group: studentapp.persistent.com
  scope: Namespaced
  names:
    kind: Database
    listKind: DatabaseList
    plural: databases
    singular: database
    shortNames:
      - db
    subresources:
      status: {}
    validation:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    version:
    - name: v1alpha1
      served: true
      storage: true