---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: studentapp-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: studentapp-operator
  template:
    metadata:
      labels:
        name: studentapp-operator
    spec:
      serviceAccountName: studentapp-operator
      containers:
        - name: studentapp-operator
          # Replace this with the built image name
          image: "quay.io/pallavw/studentapp-operator:v1.0.0"
          imagePullPolicy: "Always"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "mystudentapp-operator"
            - name: ANSIBLE_GATHERING
              value: explicit
      volumes:
        - name: runner
          emptyDir: {}